version: '3.7'

services:
  db.postgres.core:
    ports:
      - 5430:5432

  db.postgres.identity:
    ports:
      - 5432:5432
      
  transportsystems.backend.identity.signin:
    build:
      args:
        buildconfig: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  transportsystems.backend.api:
    build:
      args:
        buildconfig: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  transportsystems.backend.identity.manage:
    build:
      args:
        buildconfig: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

