version: '3.7'

services:
  reverseproxy:
    image: nginx:alpine
    ports:
      - 82:82
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  db.postgres.core:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: apiservice
      POSTGRES_DB: ts_data
    volumes:
      - postgres-core-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  db.postgres.identity:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: identityservice
      POSTGRES_DB: ts_identity
    volumes:
      - postgres-identity-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  transportsystems.backend.api:
    build:
      args:
        buildconfig: Release
      context: .
      dockerfile: Backend/API/src/Dockerfile
    restart: always
    environment:
      ConnectionStrings:db: Host=db.postgres.core;Port=5432;Database=ts_data;Username=apiservice
      ConnectionStrings:identity: "${IDENTITY}"
      ConnectionStrings:identity_manage: http://transportsystems.backend.identity.manage
    depends_on:
      - db.postgres.core
      - transportsystems.backend.identity.signin
      - transportsystems.backend.identity.manage

  transportsystems.backend.identity.signin:
    build:
      args:
        buildconfig: Release
      context: .
      dockerfile: Backend/Identity/Signin/Dockerfile
    restart: always
    environment:
      ConnectionStrings:db: Host=db.postgres.identity;Port=5432;Database=ts_identity;Username=identityservice
      SLACK: "${SLACK}"
      SMS_TOKEN: "${SMS_TOKEN}"
    depends_on:
      - db.postgres.identity

  transportsystems.backend.identity.manage:
    build:
      args:
        buildconfig: Release
      context: .
      dockerfile: Backend/Identity/Manage/Dockerfile
    restart: always
    environment:
      ConnectionStrings:db: Host=db.postgres.identity;Port=5432;Database=ts_identity;Username=identityservice
      ConnectionStrings:identity: "${IDENTITY}"
    depends_on:
      - db.postgres.identity
      - transportsystems.backend.identity.signin

volumes:
  postgres-core-data:
    external: true
  postgres-identity-data:
    external: true