version: '2.1'

services:
  db.postgres.core:
    ports:
      - 5430:5432

  db.postgres.identity:
    ports:
      - 5432:5432
      
  transportsystems.backend.identity.signin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  transportsystems.backend.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  transportsystems.backend.identity.manage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

